### ISSUE TITLE
[Very small fix needed] Fix install.sh script 

### ISSUE THREAD

**Issue by nborie** [PremierLangage/sandbox#103]
I have the following behavior 
```bash
nborie@lancelot ~/PL_LOCAL/sandbox $ sudo ./bin/install.sh 
python3: ERROR - Python 3.10.6 found, should be at least 3.7 (see: https://www.python.org/).
nborie@lancelot ~/PL_LOCAL/sandbox $ python3
\Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
nborie@lancelot ~/PL_LOCAL/sandbox $ 
```
It seems to me that 3.10.6 >= 3.7 .... It seems to come from the following lines of file `install.sh`
```bash
ver=$(python3 --version 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
if [[ "$ver" -lt "37" ]]; then
    echo "python3:$Red ERROR - $(python3 -V | tr -d '\n') found, should be at least 3.7 (see: https://www.python.org/).$Color_Off" >&2
    exit 1
fi
```
Please fix it properly with a one or two line patch

**Comment by nimdanor** [comment]
ver=$(python3 --version 2>&1 | sed 's/.* \([0-9]\).\([0-9]\)*.*/\1\2/')
if [[ "$ver" -lt "37" ]]; then
    echo "python3:$Red ERROR - $(python3 -V | tr -d '\n') found, should be at least 3.7 (see: https://www.python.org/).$Color_Off" >&2
    exit 1
fi

**Comment by NewMeeh** [comment]
fixed https://github.com/PremierLangage/sandbox/commit/e8ae3d4e9e91058b06bb8658884b904e30477913
