### ISSUE TITLE
mathics in the box

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/sandbox#32]
Pour Gilles M:
pip install mathics
installation : https://github.com/mathics/Mathics/wiki/Installing
Mathics en ligne : https://mathics.angusgriffith.com/
Github :https://github.com/mathics/Mathics

**Comment by qcoumes** [comment]
D'après ce que j'ai compris, mathics permet de faire tourner un serveur CAS. Quel est l'intérêt d'en faire tourner un sur un serveur de l'UPEM alors qu'il existe déjà des serveur existant : https://mathics.angusgriffith.com/

Dans tout les cas, il s'agit d'un serveur indépendant et n'a aucun rapport avec la sandbox

@nimdanor

**Comment by nimdanor** [comment]
C'est pour l'équipe  de Versailles . Mais comme nous n'avons pas de nouvelles depuis longtemps.
Je ferme la demande.
