### ISSUE TITLE
New Generic API

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/sandbox#42]
The current sandbox does not allow to easily implement requests other than `build` and `evaluate`.

I propose [this new API](https://documenter.getpostman.com/view/7955851/S1a915EG?version=latest) which allow to execute any bash command withing the given environment.

For instance, a build request would the `environment.tgz` alongside this JSON :

```json
{
    "command": [
        "python3 builder.py pl.json processed.json"
    ],
    "result": "processed.json",
    "keep": "P7D"
}
```

**Comment by nimdanor** [comment]
Is there security issue ? 
What is the protocol if the "command" dosen't exist or crash ?

outside of this it will help people that don't want to code the grader in python.
Ok with me.

**Comment by qcoumes** [comment]
Since every commands are still executed in a container, there's no new security issue introduced.

The sandbox can still time out after a number of seconds defined in the settings.
