### ISSUE TITLE
Apache process bug

### ISSUE THREAD

**Issue by Pavell94000** [PremierLangage/sandbox#49]
Last week, we had a problem with apache and the sandbox. The error was :
`Timeout when reading response headers from daemon process`

We  tried to fixed it with the solution given [here](https://stackoverflow.com/questions/40413171/django-webfaction-timeout-when-reading-response-headers-from-daemon-process).

To be continued... when it crashes again, or not...

**Comment by qcoumes** [comment]
Seems to bve working fine

**Comment by nimdanor** [comment]
I hope the reason it's working is well documented ....

**Comment by Pavell94000** [comment]
This bug is back tonight : 
`[Thu Oct 01 00:07:02.476561 2020] Timeout when reading response headers from daemon process 'sandbox': /srv/local/pl/pl-sandbox/pl_sandbox/wsgi.py`

This is what appears in the logs until 9:23 am, then it's this error :
`[Thu Oct 01 09:23:20.289302 2020] [wsgi:error] [pid 12861] (11)Resource temporarily unavailable: [client 193.50.159.142:40434] mod_wsgi (pid=12861): Unable to connect to WSGI daemon process 'sandbox' on '/var/run/apache2/wsgi.14315.15.1.sock' after multiple attempts as listener backlog limit was exceeded or the socket does not exist.`

Someone restarted the sandbox at 9:31

**Comment by NewMeeh** [comment]
Error doesn't seem to appear anymore.
