### ISSUE TITLE
gtts module in the sandox

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/sandbox#55]
I need a new python module in the sandbox : `gtts` .

**Comment by nimdanor** [comment]
@ddoyen Il faut avoir un accès réseau pour utiliser cette API google ?
IL n'y a pas d'accès réseau sur la sandbox.

**Comment by ddoyen** [comment]
A une époque, on pouvait, non ? Y a-t-il une raison impérative pour ce bridage ?

**Comment by Pavell94000** [comment]
Peut on fermer cette issue ? @nimdanor @ddoyen

**Comment by qcoumes** [comment]
ping @nimdanor @ddoyen

**Comment by nimdanor** [comment]
oui
