### ISSUE TITLE
Another implementation of the sandbox

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/sandbox#6]
We must do a test and compare of https://github.com/edx/codejail.
If it works we will not have the need to maintain it ?

**Comment by nimdanor** [comment]
il faut installer dans l'image docker les logiciels:
 apparmor, firejail

**Comment by qcoumes** [comment]
Any other implementation must be try on another branch.

**Comment by nimdanor** [comment]
Ok let's add Nicolas S to the project.

**Comment by qcoumes** [comment]
No update for a year, what should I do about this issue ?

**Comment by nimdanor** [comment]
i think the 3.0.0 version is a new implemntatioin ;)
