### ISSUE TITLE
[Enhancement] Add an Haskell compiler to the sandbox

### ISSUE THREAD

**Issue by nborie** [PremierLangage/sandbox#71]
On an Ubuntu up to date (20.04), It is enough to add 

    sudo apt-get install ghc 
    sudo apt-get install libbsd-dev

Probably same packages for the Debian... New recruits can probably deal with this issue... Leave question here to the senior docker developer qcoumes if needed.

For the curious (and/if you need to test), here is an hello world in haskell

    nborie@bayer:~$ cat hello_world.hs
    module Main where
    
    main :: IO()
    main = putStrLn "Hello World !"
    nborie@bayer:~$ ghc -o hello hello_world.hs 
    [1 of 1] Compiling Main             ( hello_world.hs, hello_world.o )
    Linking hello ...
    nborie@bayer:~$ ./hello 
    Hello World !
    nborie@bayer:~$

**Comment by mciissee** [comment]
You can test the install on https://www.platon-edu.fr/editor before we integrate it on pl.upem.fr

**Comment by nborie** [comment]
It works on platon-edu. Thank you.
![test_haskell](https://user-images.githubusercontent.com/6042616/99822634-c1490480-2b53-11eb-9f6d-9c1f768f2c95.png)

**Comment by mciissee** [comment]
Nice I will close this issue once the sandbox will be deployed on [https://pl.u-pem.fr](https://pl.u-pem.fr) server

**Comment by mciissee** [comment]
done
