### ISSUE TITLE
[enhancement] Add the Glasgow Haskell Compiler to the sandbox 3.0.x

### ISSUE THREAD

**Issue by nborie** [PremierLangage/sandbox#74]
`ghc` is no more installed on version 3.0.x of the sandbox. Please, re-add it in the dockerfile...

**Comment by nborie** [comment]
The fix work properly for me...

the `master` branch of the sandbox is now compatible with the branch `add_new_sandbox` of premierlangage repository with the Glasgow Haskell Compiler

**Comment by mciissee** [comment]
Nice !
